version: "3.5"

services:
  # ----------------------------------------
  # MARIADB
  # ----------------------------------------
  db:
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=m0nm@r1adbr00t
      - MYSQL_USER=nhl
      - MYSQL_PASSWORD=nhl2021

  # ----------------------------------------
  # ADMINER
  # ----------------------------------------
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=nette
    ports:
      - 9080:8080

  # ----------------------------------------
  # ADMINER
  # ----------------------------------------
  nhl:
    # image: ghcr.io/raphyli/nhl-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    image: devops/nhl-bot:latest
    container_name: nhl
    restart: always
    depends_on:
      - db
    environment:
      - SLACK_SIGNING_SECRET=ea2a23e8768e22b747ad558696ca88ae
      - SLACK_CLIENT_ID=1620933655654.1633894684132
      - SLACK_CLIENT_SECRET=dee4b4e2d58d527285d1feb3f18c3811
      - SLACK_STATE_SECRET=
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=nhl
      - DB_PASSWORD=nhl2021
      - DB_DATABASE=nhl
    ports:
      - 3000:3000
