FROM node:12

ARG SLACK_SIGNING_SECRET=$SLACK_SIGNING_SECRET
ARG SLACK_CLIENT_ID=$SLACK_CLIENT_ID
ARG SLACK_CLIENT_SECRET=$SLACK_CLIENT_SECRET
ARG SLACK_STATE_SECRET:$SLACK_STATE_SECRET
ARG DB_HOST:$DB_HOST
ARG DB_PORT:$DB_PORT
ARG DB_USER:$DB_USER
ARG DB_PASSWORD:$DB_PASSWORD
ARG DB_DATABASE:$DB_DATABASE
ARG DEBUG:#DEBUG

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

CMD [ "npm", "start:prod" ]
